"""empty message

Revision ID: c934ef3696c5
Revises: 4eea48a18426
Create Date: 2022-02-19 09:57:40.615201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c934ef3696c5'
down_revision = '4eea48a18426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'title')
    # ### end Alembic commands ###
