"""empty message

Revision ID: e8c00830e317
Revises: 742d357afb00
Create Date: 2022-02-19 18:39:57.413672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c00830e317'
down_revision = '742d357afb00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_details', 'price')
    op.drop_column('order_details', 'total')
    op.drop_column('order_details', 'sales_tax')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('sales_tax', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False))
    op.add_column('order_details', sa.Column('total', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False))
    op.add_column('order_details', sa.Column('price', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
