"""empty message

Revision ID: 742d357afb00
Revises: 715564e09188
Create Date: 2022-02-19 13:13:48.156464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742d357afb00'
down_revision = '715564e09188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('order_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_details', 'order_number')
    # ### end Alembic commands ###
