"""empty message

Revision ID: 50672a4b11f9
Revises: e8c00830e317
Create Date: 2022-02-19 18:40:25.613407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50672a4b11f9'
down_revision = 'e8c00830e317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('price', sa.String(length=20), nullable=False))
    op.add_column('order_details', sa.Column('sales_tax', sa.String(length=20), nullable=False))
    op.add_column('order_details', sa.Column('total', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_details', 'total')
    op.drop_column('order_details', 'sales_tax')
    op.drop_column('order_details', 'price')
    # ### end Alembic commands ###
